### ISSUE TITLE
I/O reactor status : STOPPED

### ISSUE THREAD

**Issue by Zixell** [Philippus/elastic4s#3089]
Version: 7.1.0

![image](https://github.com/Philippus/elastic4s/assets/28920883/7aa97958-5643-4af4-9c74-bc478f8f56a9)

We are having these errors occasionally, for some reason ES client after fail killing IO Reactor and it is not recovering, so the only thing we can do to fix it - is restarting our service.

I've tried to implement custom exception handler for IO reactor and pass it to _httpClientBuilder_ but in our case it brakes our SSL config and causes for problems then it solves. 

```
override val restClient: RestClient = RestClient
    .builder(elasticHosts: _*)
    .setRequestConfigCallback(NoOpRequestConfigCallback)
    .setHttpClientConfigCallback(new HttpClientConfigCallback {
      override def customizeHttpClient(httpClientBuilder: HttpAsyncClientBuilder): HttpAsyncClientBuilder = {
        if (withBasicAuth) httpClientBuilder.setDefaultCredentialsProvider(getCredentialsProvider)
        if (isASecureConnection) httpClientBuilder.setSSLContext(getContextJDK(configuration))
        httpClientBuilder.setDefaultIOReactorConfig(IOReactorConfig.custom()
          .setSoKeepAlive(true)
          .build())
      }
    })
    .build()

  override val client: ElasticClient = ElasticClient(JavaClient.fromRestClient(restClient))
```

This is out rest client configuration. 

Anyway, my question is: is it a known issue and if so, maybe it was fixed in newer versions? I found somewhere that it is was fixed in 7.16.3 but could find any evidence of that.

Feel free to ask any other information! As I found online many people experiencing the same issue, but I couldn't find solid solution for this, so I decided to create an Issue.

**Comment by Philippus** [comment]
I don't think this is an issue with elastic4s, but maybe with Elasticsearch itself?

**Comment by Zixell** [comment]
Figured it out, problem is outside of elastic4s

**Comment by kubinio123** [comment]
@Zixell what was the issue in your case? From my readings it's also an issue with underlying java http components due to some poor design choices (see the issue, and this [comment](https://github.com/elastic/elasticsearch/issues/49124#issuecomment-693716231)). But the behaviour from elastic4s side is the same in our case. When this error happens the client is dead and service needs a restart. 

We worked around this by implementing a recoverable client with same interface as base `ElasticClient`, which based on underlying reactor status will recreate and retry all failed requests. I think such recovery could be a part of the Elastic4s itself...
